第三题的意思是：要从49种蔬菜挑选27-33种，每种补货量$\geq 2.5$

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data\\附件2.csv")
df['销售日期'] = pd.to_datetime(df['销售日期'])
# 设置时间戳列为索引（如果尚未设置）
df.set_index('销售日期', inplace=True)
df['日期'] = df.index

# 选择2023年6月24日到30日的数据
start_date = '2023-06-24'
end_date = '2023-06-30'
selected_data = df[start_date:end_date]
selected_data.head()

,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,日期
销售日期,,,,,,,
2023-06-24,10:47.3,102900011032022,1.000,2.8,销售,否,2023-06-24
2023-06-24,10:47.5,102900005115786,0.379,4.0,销售,否,2023-06-24
2023-06-24,13:51.8,102900005115762,0.505,4.0,销售,否,2023-06-24
2023-06-24,14:43.8,102900005115762,0.505,4.0,销售,否,2023-06-24
2023-06-24,14:44.0,102900011030059,1.000,4.5,销售,否,2023-06-24

In [3]:
vegetable_names = selected_data["单品编码"].tolist()
# 使用集合（set）来去除重复项
vegetable_names = set(vegetable_names)
# 将集合转换回列表
vegetable_names = list(vegetable_names)
len(vegetable_names)

49

In [4]:
df3 = pd.read_excel("data\\附件3.xlsx")
df3.columns = ["日期", "单品编码", "批发价格(元/千克)"]

In [5]:
df_1 = selected_data.merge(df3, on=['日期', '单品编码'], how='left')
df_1.head(10)

,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售,日期,批发价格(元/千克)
0,10:47.3,102900011032022,1.000,2.8,销售,否,2023-06-24,1.51
1,10:47.5,102900005115786,0.379,4.0,销售,否,2023-06-24,2.41
2,13:51.8,102900005115762,0.505,4.0,销售,否,2023-06-24,2.31
3,14:43.8,102900005115762,0.505,4.0,销售,否,2023-06-24,2.31
4,14:44.0,102900011030059,1.000,4.5,销售,否,2023-06-24,3.32
5,14:44.4,102900011030059,1.000,4.5,销售,否,2023-06-24,3.32
6,19:55.5,102900005115823,0.477,8.0,销售,否,2023-06-24,4.32
7,19:55.7,102900011006948,0.485,12.0,销售,否,2023-06-24,7.66
8,22:36.5,102900005115250,0.271,24.0,销售,否,2023-06-24,15.60
9,25:27.8,102900051000463,0.415,8.0,销售,否,2023-06-24,5.38

In [6]:
df4 = pd.read_excel("data\\附件4.xlsx", sheet_name="Sheet1")
df4.head()

              单品编码     单品名称  损耗率(%)
0  102900005115168     牛首生菜    4.39
1  102900005115199    四川红香椿   10.46
2  102900005115250  西峡花菇(1)   10.80
3  102900005115625   本地小毛白菜    0.18
4  102900005115748      白菜苔    8.78

In [7]:
df_2 = df_1.merge(df4, on=['单品编码'], how='left').drop(["扫码销售时间", "销售类型", "是否打折销售", "单品编码"], axis=1)
df_2.head()

   销量(千克)  销售单价(元/千克)         日期  批发价格(元/千克)     单品名称  损耗率(%)
0   1.000         2.8 2023-06-24        1.51   小皱皮(份)    9.43
1   0.379         4.0 2023-06-24        2.41      竹叶菜   13.62
2   0.505         4.0 2023-06-24        2.31       苋菜   18.52
3   0.505         4.0 2023-06-24        2.31       苋菜   18.52
4   1.000         4.5 2023-06-24        3.32  云南生菜(份)    9.43

In [8]:
def devide(df):
    # 获取分类特征的所有唯一值
    categories = df["单品名称"].unique()

    # 创建一个空的字典，用于存储划分后的DataFrame
    dfs_by_category = {}

    # 按分类特征划分DataFrame
    for category in categories:
        dfs_by_category[category] = df[df["单品名称"] == category]

    # 将每个划分后的DataFrame写入CSV文件
    for category, df_category in dfs_by_category.items():
        csv_filename = f'data_3\{category}.csv'  
        df_category.to_csv(csv_filename, encoding='gbk', index=False)  

devide(df_2)